# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Spreadsheet-SimpleExcel
version:      1.5
version_from: lib/Spreadsheet/SimpleExcel.pm
installdirs:  site
requires:
    IO::File:                      1.10
    IO::Scalar:                    0
    Spreadsheet::WriteExcel:       0
    XML::Writer:                   0.600

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
